# Overview

Goal of this notebook is to create the train/test/holdout splits for the project.

For the splits themselves, we want to pull one row per building. In this data basically every building shows up multiple times, so we only want a single instance of that building to train/test on.

In [38]:
import polars as pl
from src.helpers.eda import get_column_value_frequency

data_directory = "../../data/energy"
df = pl.read_parquet(f"{data_directory}/s_energy.parquet")

In [39]:
df

shape: (36_428, 13)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ OSEBuildin ┆ DataYear ┆ BuildingN ┆ BuildingT ┆ … ┆ EPAProper ┆ EUI       ┆ EUI_WN    ┆ Year2025 │
│ gID        ┆ ---      ┆ ame       ┆ ype       ┆   ┆ tyType    ┆ ---       ┆ ---       ┆ ---      │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ bool     │
│ i64        ┆          ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2          ┆ 2025     ┆ Paramount ┆ NonReside ┆ … ┆ Hotel     ┆ 69.3      ┆ 69        ┆ true     │
│            ┆          ┆ Hotel     ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│ 3          ┆ 2025     ┆ Westin    ┆ NonReside ┆ … ┆ Hotel     ┆ 89.9      ┆ 89.9      ┆ true     │
│            ┆          ┆ Hotel     ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ (Parent   ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Building) ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5          ┆ 2025     ┆ Hotel Max ┆ NonReside ┆ … ┆ Hotel     ┆ 83.6      ┆ 83.2      ┆ true     │
│            ┆          ┆           ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│ 8          ┆ 2025     ┆ Warwick   ┆ NonReside ┆ … ┆ Hotel     ┆ 86.1      ┆ 85.7      ┆ true     │
│            ┆          ┆ Seattle   ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Hotel     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9          ┆ 2025     ┆ West      ┆ NonReside ┆ … ┆ Police    ┆ 172.1     ┆ 171.7     ┆ true     │
│            ┆          ┆ Precinct  ┆ ntial     ┆   ┆ Station   ┆           ┆           ┆          │
│            ┆          ┆ (Seattle  ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Police)   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 50038      ┆ 2015     ┆ Salmon    ┆ NonReside ┆ … ┆ Mixed Use ┆ 26.799999 ┆ 29.100000 ┆ false    │
│            ┆          ┆ Bay       ┆ ntial     ┆   ┆ Property  ┆ 24        ┆ 38        ┆          │
│            ┆          ┆ Marine    ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Center    ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ West      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50049      ┆ 2015     ┆ PACIFIC   ┆ Multifami ┆ … ┆ Multifami ┆ 25.600000 ┆ 27.799999 ┆ false    │
│            ┆          ┆ CENTER    ┆ ly LR     ┆   ┆ ly LR     ┆ 38        ┆ 24        ┆          │
│            ┆          ┆ CONDOMINI ┆ (1-4)     ┆   ┆ (1-4)     ┆           ┆           ┆          │
│            ┆          ┆ UM        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50055      ┆ 2015     ┆ NORA      ┆ Multifami ┆ … ┆ Multifami ┆ 48.599998 ┆ 55.099998 ┆ false    │
│            ┆          ┆ (IDENTITY ┆ ly MR     ┆   ┆ ly MR     ┆ 47        ┆ 47        ┆          │
│            ┆          ┆ APTS      ┆ (5-9)     ┆   ┆ (5-9)     ┆           ┆           ┆          │
│            ┆          ┆ 4123)     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50057      ┆ 2015     ┆ CIRRUS    ┆ Multifami ┆ … ┆ Multifami ┆ 52.700000 ┆ 61.400001 ┆ false    │
│            ┆          ┆           ┆ ly HR     ┆   ┆ ly HR     ┆ 76        ┆ 53        ┆          │
│            ┆          ┆           ┆ (10+)     ┆   ┆ (10+)     ┆           ┆           ┆          │
│ 50219      ┆ 2015     ┆ Garfield  ┆ NonReside ┆ … ┆ Other -   ┆ 76.599998 ┆ 97.800003 ┆ false    │
│            ┆          ┆ Community ┆ ntial     ┆   ┆ Recreatio ┆ 47        ┆ 05        ┆          │
│            ┆          ┆ Center    ┆           ┆   ┆ n         ┆           ┆           ┆          │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [52]:
with pl.Config(tbl_rows=-1):
    print(
        df
        .select("PropertyGFABuildings")
        .with_columns((pl.col("PropertyGFABuildings").str.replace(pattern=",", value="").alias("PropertyGFABuildingsFIXED")))
        .head(100)
    )

shape: (100, 2)
┌──────────────────────┬───────────────────────────┐
│ PropertyGFABuildings ┆ PropertyGFABuildingsFIXED │
│ ---                  ┆ ---                       │
│ str                  ┆ str                       │
╞══════════════════════╪═══════════════════════════╡
│ 88,502               ┆ 88502                     │
│ 759,392              ┆ 759392                    │
│ 61,320               ┆ 61320                     │
│ 113,580              ┆ 113580                    │
│ 60,090               ┆ 60090                     │
│ 102,761              ┆ 102761                    │
│ 163,984              ┆ 163984                    │
│ 62,216               ┆ 62216                     │
│ 133,884              ┆ 133884                    │
│ 272,015              ┆ 272015                    │
│ 65,009               ┆ 65009                     │
│ 295,511              ┆ 295511                    │
│ 67,390               ┆ 67390                     │
│ 355,000              ┆ 355000                    │
│ 103,911              ┆ 103911                    │
│ 375,902              ┆ 375902                    │
│ 57,452               ┆ 57452                     │
│ 104,352              ┆ 104352                    │
│ 540,360              ┆ 540360                    │
│ 339,315              ┆ 339315                    │
│ 56,228               ┆ 56228                     │
│ 58,006               ┆ 58006                     │
│ 133,585              ┆ 133585                    │
│ 126,351              ┆ 126351                    │
│ 52,210               ┆ 52210                     │
│ 160,645              ┆ 160645                    │
│ 51,582               ┆ 51582                     │
│ 87,262               ┆ 87262                     │
│ 81,871               ┆ 81871                     │
│ 26,225               ┆ 26225                     │
│ 2,026,324            ┆ 2026,324                  │
│ 54,986               ┆ 54986                     │
│ 175,565              ┆ 175565                    │
│ 52,554               ┆ 52554                     │
│ 175,015              ┆ 175015                    │
│ 70,586               ┆ 70586                     │
│ 126,240              ┆ 126240                    │
│ 165,202              ┆ 165202                    │
│ 64,597               ┆ 64597                     │
│ 926,614              ┆ 926614                    │
│ 57,420               ┆ 57420                     │
│ 122,810              ┆ 122810                    │
│ 115,718              ┆ 115718                    │
│ 88,100               ┆ 88100                     │
│ 118,858              ┆ 118858                    │
│ 56,072               ┆ 56072                     │
│ 78,051               ┆ 78051                     │
│ 54,984               ┆ 54984                     │
│ 296,313              ┆ 296313                    │
│ 63,371               ┆ 63371                     │
│ 78,972               ┆ 78972                     │
│ 179,014              ┆ 179014                    │
│ 76,631               ┆ 76631                     │
│ 96,783               ┆ 96783                     │
│ 287,367              ┆ 287367                    │
│ 238,097              ┆ 238097                    │
│ 932,000              ┆ 932000                    │
│ 65,127               ┆ 65127                     │
│ 396,085              ┆ 396085                    │
│ 571,329              ┆ 571329                    │
│ 52,000               ┆ 52000                     │
│ 262,048              ┆ 262048                    │
│ 63,888               ┆ 63888                     │
│ 616,891              ┆ 616891                    │
│ 50,283               ┆ 50283                     │
│ 81,560               ┆ 81560                     │
│ 60,953               ┆ 60953                     │
│ 75,364               ┆ 75364                     │
│ 67,743               ┆ 67743                     │
│ 161,514              ┆ 161514                    │
│ 63,681               ┆ 63681                     │
│ 60,725               ┆ 60725                     │
│ 59,955               ┆ 59955                     │
│ 93,218               ┆ 93218                     │
│ 56,521               ┆ 56521                     │
│ 51,390               ┆ 51390                     │
│ 131,013              ┆ 131013                    │
│ 245,587              ┆ 245587                    │
│ 69,138               ┆ 69138                     │
│ 66,588               ┆ 66588                     │
│ 44,324               ┆ 44324                     │
│ 82,746               ┆ 82746                     │
│ 169,037              ┆ 169037                    │
│ 174,000              ┆ 174000                    │
│ 302,661              ┆ 302661                    │
│ 55,513               ┆ 55513                     │
│ 61,156               ┆ 61156                     │
│ 59,000               ┆ 59000                     │
│ 289,588              ┆ 289588                    │
│ 122,976              ┆ 122976                    │
│ 529,343              ┆ 529343                    │
│ 96,300               ┆ 96300                     │
│ 67,356               ┆ 67356                     │
│ 254,523              ┆ 254523                    │
│ 78,804               ┆ 78804                     │
│ 66,994               ┆ 66994                     │
│ 103,166              ┆ 103166                    │
│ 54,765               ┆ 54765                     │
│ 89,821               ┆ 89821                     │
│ 53,016               ┆ 53016                     │
└──────────────────────┴───────────────────────────┘

## Examine grain to motivate future methods

In [40]:
(
    df
    .group_by("OSEBuildingID")
    .len()
    .sort("len", descending=True)
)

shape: (3_785, 2)
┌───────────────┬─────┐
│ OSEBuildingID ┆ len │
│ ---           ┆ --- │
│ i64           ┆ u32 │
╞═══════════════╪═════╡
│ 27829         ┆ 11  │
│ 19671         ┆ 11  │
│ 423           ┆ 11  │
│ 27707         ┆ 11  │
│ 19668         ┆ 11  │
│ …             ┆ …   │
│ 50956         ┆ 1   │
│ 52022         ┆ 1   │
│ 52031         ┆ 1   │
│ 51998         ┆ 1   │
│ 52028         ┆ 1   │
└───────────────┴─────┘

In [41]:
(
    df
    .group_by("OSEBuildingID", "DataYear")
    .len()
    .sort("len", descending=True)
)

shape: (36_428, 3)
┌───────────────┬──────────┬─────┐
│ OSEBuildingID ┆ DataYear ┆ len │
│ ---           ┆ ---      ┆ --- │
│ i64           ┆ i64      ┆ u32 │
╞═══════════════╪══════════╪═════╡
│ 20017         ┆ 2021     ┆ 1   │
│ 27264         ┆ 2017     ┆ 1   │
│ 21774         ┆ 2019     ┆ 1   │
│ 49710         ┆ 2025     ┆ 1   │
│ 26898         ┆ 2023     ┆ 1   │
│ …             ┆ …        ┆ …   │
│ 50148         ┆ 2023     ┆ 1   │
│ 25743         ┆ 2015     ┆ 1   │
│ 20071         ┆ 2018     ┆ 1   │
│ 24537         ┆ 2024     ┆ 1   │
│ 26986         ┆ 2023     ┆ 1   │
└───────────────┴──────────┴─────┘

## Set it all up

Plan:

In [47]:
final_year_set = df.filter(pl.col("DataYear") == 2025)

buildings = (
    final_year_set
    .select("OSEBuildingID")
    .unique()
    .shape[0]
)
print(f"\nNumber of Buildings in Dataset: {buildings}\n")

Number of Buildings in Dataset: 3462

In [45]:
# Goal:
df_shuffled = (
    df
    .filter(
        pl.int_range(0, pl.len())
        .shuffle(seed=101)
        .over("OSEBuildingID") == 0
    )
)

df_shuffled

shape: (3_785, 13)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ OSEBuildin ┆ DataYear ┆ BuildingN ┆ BuildingT ┆ … ┆ EPAProper ┆ EUI       ┆ EUI_WN    ┆ Year2025 │
│ gID        ┆ ---      ┆ ame       ┆ ype       ┆   ┆ tyType    ┆ ---       ┆ ---       ┆ ---      │
│ ---        ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ bool     │
│ i64        ┆          ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆          │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 830        ┆ 2025     ┆ Cascade   ┆ NonReside ┆ … ┆ Office    ┆ 29.1      ┆ 28.9      ┆ true     │
│            ┆          ┆ Public    ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Media (Fo ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ rmerly…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 19537      ┆ 2025     ┆ Alki Elem ┆ School    ┆ … ┆ K-12      ┆ 14.2      ┆ 14.2      ┆ true     │
│            ┆          ┆ entary    ┆           ┆   ┆ School    ┆           ┆           ┆          │
│            ┆          ┆ School &  ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ Commu…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 22701      ┆ 2025     ┆ Victory   ┆ NonReside ┆ … ┆ Other     ┆ 4,474.8   ┆ 4,473.8   ┆ true     │
│            ┆          ┆ Studios   ┆ ntial     ┆   ┆           ┆           ┆           ┆          │
│ 24371      ┆ 2025     ┆ Bb House  ┆ Multifami ┆ … ┆ Multifami ┆ 25.5      ┆ 25.3      ┆ true     │
│            ┆          ┆           ┆ ly LR     ┆   ┆ ly        ┆           ┆           ┆          │
│            ┆          ┆           ┆ (1-4)     ┆   ┆ Housing   ┆           ┆           ┆          │
│ 24514      ┆ 2025     ┆ Oak Tree  ┆ NonReside ┆ … ┆ Supermark ┆ 193.4     ┆ 193.4     ┆ true     │
│            ┆          ┆ Plaza -   ┆ ntial     ┆   ┆ et/Grocer ┆           ┆           ┆          │
│            ┆          ┆ Supermark ┆           ┆   ┆ y Store   ┆           ┆           ┆          │
│            ┆          ┆ et        ┆           ┆   ┆           ┆           ┆           ┆          │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 24351      ┆ 2016     ┆ 1964 4TH  ┆ NonReside ┆ … ┆ Non-Refri ┆ 34.900001 ┆ 37.200000 ┆ false    │
│            ┆          ┆ AVE S     ┆ ntial     ┆   ┆ gerated   ┆ 53        ┆ 76        ┆          │
│            ┆          ┆           ┆           ┆   ┆ Warehouse ┆           ┆           ┆          │
│ 27016      ┆ 2016     ┆ PACIFIC   ┆ NonReside ┆ … ┆ Office    ┆ 43.200000 ┆ 46.400001 ┆ false    │
│            ┆          ┆ GEORGETOW ┆ ntial     ┆   ┆           ┆ 76        ┆ 53        ┆          │
│            ┆          ┆ N CENTER  ┆           ┆   ┆           ┆           ┆           ┆          │
│            ┆          ┆ LLC       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 27455      ┆ 2016     ┆ Queen     ┆ Multifami ┆ … ┆ Distribut ┆ 18.299999 ┆ 20.5      ┆ false    │
│            ┆          ┆ Anne      ┆ ly LR     ┆   ┆ ion       ┆ 24        ┆           ┆          │
│            ┆          ┆ Exchange  ┆ (1-4)     ┆   ┆ Center    ┆           ┆           ┆          │
│ 25654      ┆ 2015     ┆ FISHER    ┆ NonReside ┆ … ┆ Retail    ┆ 9         ┆ 9         ┆ false    │
│            ┆          ┆ BUILDING  ┆ ntial     ┆   ┆ Store     ┆           ┆           ┆          │
│ 26190      ┆ 2015     ┆ ELLENBERT ┆ Multifami ┆ … ┆ Multifami ┆ 80.199996 ┆ 99.599998 ┆ false    │
│            ┆          ┆ APTS      ┆ ly LR     ┆   ┆ ly LR     ┆ 95        ┆ 47        ┆          │
│            ┆          ┆           ┆ (1-4)     ┆   ┆ (1-4)     ┆           ┆           ┆          │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
(
    df_shuffled
    .group_by("OSEBuildingID")
    .len()
    .sort("len", descending=True)
)

shape: (3_732, 2)
┌───────────────┬─────┐
│ OSEBuildingID ┆ len │
│ ---           ┆ --- │
│ i64           ┆ u32 │
╞═══════════════╪═════╡
│ 49703         ┆ 1   │
│ 24560         ┆ 1   │
│ 50638         ┆ 1   │
│ 414           ┆ 1   │
│ 20868         ┆ 1   │
│ …             ┆ …   │
│ 50715         ┆ 1   │
│ 50694         ┆ 1   │
│ 23163         ┆ 1   │
│ 29612         ┆ 1   │
│ 27361         ┆ 1   │
└───────────────┴─────┘

In [44]:
get_column_value_frequency(df_shuffled, "DataYear")

Collecting <DataYear> Values ---

shape: (11, 2)
┌──────────┬───────┐
│ DataYear ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 2015     ┆ 562   │
│ 2016     ┆ 2567  │
│ 2017     ┆ 26    │
│ 2018     ┆ 146   │
│ 2019     ┆ 26    │
│ …        ┆ …     │
│ 2021     ┆ 3     │
│ 2022     ┆ 1     │
│ 2023     ┆ 5     │
│ 2024     ┆ 18    │
│ 2025     ┆ 236   │
└──────────┴───────┘